force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <description>Object responsible for storing photos in Salesforce</description>
    <label>Photo</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Photo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo__c/fields/AlbumId__c.field-meta.xml
<CustomField>
    <fullName>AlbumId__c</fullName>
    <label>Album Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/ThumbnailURL__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL__c</fullName>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PhotosController.cls
public with sharing class PhotosController {

    @AuraEnabled(cacheable=true)
    public static List<Photo__c> getPhotos(Integer numberOfRows, String title){
        if (String.isEmpty(title)){
            return [SELECT Id, Title__c, URL__c, ThumbnailURL__c, AlbumId__c, ExternalId__c FROM Photo__c LIMIT 200];
        }
        String searchKey = '%' + title + '%';
        return [SELECT Id, Title__c, URL__c, ThumbnailURL__c, AlbumId__c, ExternalId__c FROM Photo__c WHERE Title__c LIKE :searchKey LIMIT 200];

    }

    @AuraEnabled
    public static void sendEmail(List<Photo__c> photos){
        PhotosEmailService emailService = new PhotosEmailService();

        emailService.setPhotosToSend(photos);
        emailService.sendPhotos();
    }
}