force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <description>Object responsible for storing photos in Salesforce</description>
    <label>Photo</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Photo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo__c/fields/AlbumId__c.field-meta.xml
<CustomField>
    <fullName>AlbumId__c</fullName>
    <label>Album Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/ThumbnailURL__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL__c</fullName>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PhotosIntegrationService.cls
public with sharing class PhotosIntegrationService {

    public void getPhotosFromRemote(){
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:PhotosIntegration');
        req.setMethod('GET');

        Http http = new Http();
        HttpResponse res = http.send(req);
  
        Photo[] photos = Photo.parse(res.getBody());

        savePhotos(photos);
    }

    private void savePhotos(List<Photo> photos){

        List<Photo__c> photosToInsert = new List<Photo__c>();
        List<Photo__c> photosToUpdate = new List<Photo__c>();
        List<Integer> externalIds = new List<Integer>();
        for (Photo ph : photos){
            externalIds.add(ph.Id);
        }
        
        List<Photo__c> notExistingPhotos = [SELECT Id, ExternalId__c FROM Photo__c WHERE ExternalId__c NOT IN :externalIds];
        delete notExistingPhotos;

        List<Photo__c> existingPhotos = [SELECT Id, ExternalId__c FROM Photo__c WHERE ExternalId__c IN :externalIds];
        for (Photo newPhoto : photos){
            for (Photo__c photoInDb : existingPhotos){
                if (newPhoto.Id == photoInDb.ExternalId__c){
                
                    photoInDb.Title__c = newPhoto.title;
                    photoInDb.AlbumId__c = newPhoto.albumId;
                    photoInDb.URL__c = newPhoto.url;
                    photoInDb.ThumbnailURL__c = newPhoto.thumbnailUrl;
    
                    photosToUpdate.add(photoInDb);
                    break;
                }
            }
            Photo__c photo = new Photo__c(
                Title__c = newPhoto.title,
                AlbumId__c = newPhoto.albumId,
                ExternalId__c = newPhoto.id,
                URL__c = newPhoto.url,
                ThumbnailURL__c = newPhoto.thumbnailUrl
            );
            photosToInsert.add(photo);
        }
        insert photosToInsert;
        update photosToUpdate;
    }
 
}