force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <description>Object responsible for storing photos in Salesforce</description>
    <label>Photo</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Photo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo__c/fields/AlbumId__c.field-meta.xml
<CustomField>
    <fullName>AlbumId__c</fullName>
    <label>Album Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/ThumbnailURL__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailURL__c</fullName>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PhotosServiceTest.cls
@isTest
public with sharing class PhotosServiceTest {

    private static PhotosIntegrationService service = new PhotosIntegrationService();

    @TestSetup
    static void makeData(){
        String data = '[{ "albumId": 1, "id": 1, "title": "accusamus beatae ad facilis cum similique qui sunt", "url": "https://via.placeholder.com/600/92c952", "thumbnailUrl": "https://via.placeholder.com/150/92c952" },{ "albumId": 1, "id": 3, "title": "officia porro iure quia iusto qui ipsa ut modi", "url": "https://via.placeholder.com/600/24f355", "thumbnailUrl": "https://via.placeholder.com/150/24f355" }]';
        service.savePhotos((List<Photo>) System.JSON.deserialize(data, List<Photo>.class));
    }
    
    @isTest
    static void testGetPhotosFromRemote(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new PhotosGetHttpResponseMock());
        service.getPhotosFromRemote();

        List<Photo__c> photos = [SELECT Id FROM Photo__c];
        Test.stopTest();
        System.assertEquals(3, photos.size());
    }

    @isTest
    static void testSendEmail(){
        PhotosController.sendEmail([SELECT Id, URL__c, ThumbnailURL__c, Title__c, AlbumId__c, ExternalId__c FROM Photo__c LIMIT 10], 'test@org.com');
    }

}